ALICLOUD_ACCESS_KEY: ENC[AES256_GCM,data:o6IO8a2QMSEw7EMGAb9PLQiQdo7+Qa0Q,iv:kQKMQCRscoIg/Eb1UEYgQjfVg7D57a2crSKLOMrebA4=,tag:hzu9hEG8rB2xrAtjMneTaQ==,type:str]
ALICLOUD_SECRET_KEY: ENC[AES256_GCM,data:S67WMDDa1Ht222bUOO1XMFp7cZLh/3NsqqrIYQ+Y,iv:jAl7Poo1qCaNpXvkY5nvl1Am1qw7qcRUaehQzh2+/Q4=,tag:IcHkrcRMIHYvXrXE0ZQsKg==,type:str]
AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Evlb2Id27yYe5wzZjeNFbnqsL4s=,iv:aRv6qMacIyNdZk2aP++dTy8zKwRHUgXuLhIQqZOQksI=,tag:AM6T2RrxZBbKLbv6J1YHqQ==,type:str]
AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:qEhmicvDbOShMabO4a/FdNiJwvJVR/gDUGmR+3PXaGbdmQKOzvzKOA==,iv:VbpLU9a5snIojkPqKR3AmZid/+cfGY6/WjR7XTl7bI4=,tag:KVyN4pfUi3qGc/wmOUczEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-02-18T16:32:07Z"
    mac: ENC[AES256_GCM,data:DDMeS4Sm3KXiHaOcKplYE1oNBh2JMZX2mTv4jFqoIMTPfITntWmNJnlPptnxktxVNmW7gK0GjE4CuWDecQxUG+j+tI3ME/BRu0fS3HyTgI3jLi56grIVR6YQnUZKt4MP8VaAaKEv7dCOeBpGo1Ftk0pC3prfHNySUSTim944Bzo=,iv:33Pv9opxc5O90jKY/r9+QPHIOwJsOkgXzMVbDDlrHeA=,tag:lUsc3b8BFrXtNDhhbW4TCQ==,type:str]
    pgp:
        - created_at: "2024-02-18T16:32:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DZSODbPSZIlESAQdAjeQnQ/KeOKV04VWtkl3tw6Vd30BsUBqZRMia1ugP3FUw
            w3nx62sij0gIanPFb7gSiafqwChWz3Rut0MhJpQn6aUIgwVRskeoKvIjWEBNRhnP
            0l4B7ih8UIJllro0GEXKODs8ASWUwfsM6URVRct1vw3jCbM1oDcZD25Elu/Yd1XM
            UTygJj4UW6KMEL0n/4VW/3Vvo5m8q6SQNmvbKaw9IhZMM8xbln0+TyPSFj8JQguj
            =t0GS
            -----END PGP MESSAGE-----
          fp: 8CC5C91F72DB57DA20BD848C6523836CF4992251
    unencrypted_suffix: _unencrypted
    version: 3.8.1
