aliyun:
    access_key: ENC[AES256_GCM,data:om7IIgnUCKP5rjr3hLPnQxzT9TxUM53+,iv:F7TkXyysh+bJzFgLjXXENh6TW5dcJAp45F56tYtw5Vo=,tag:Hv2lKwuxkgb8uUmmF7juwQ==,type:str]
    secret_key: ENC[AES256_GCM,data:LyVucm4u3yV1dwS7erqHJRGHl4VUTX5+bD0Le9VB,iv:LD10CqO40uG22I9LuVLJBUSinR8eZROjr3ggBE+8p7w=,tag:d70bVJtFJKETk9sIUUoLuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v6lnkm7prm0dpmcdpvn44v50rpfkzsed5uv3znxt4grsd5y6sv5qjru9qq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TE9ZVG1PUmljbyszUXpN
            dlYwRU1mbmNia25lYlBtQXcrM1JSR2FaL0RVCllVZ0tDZGQ2U2lPdUJDVWJEeWpL
            dUhESkQycHlpNXJ6ZXZkeEJFWXBwM00KLS0tIHFrVU4rcENDM2Rqby90dDhLYmt2
            Nmo0M0hkcHJzdmlTODRDT3p1S1MxM3cKt7xUWWmbDqCLrdTZuJVh0yr/TPyBSY4M
            vyJajgZbWPw0vPv2wbmf3NgdM0jTHWLFo+8pvcYtvSz7iwOXWnTFjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-21T15:42:15Z"
    mac: ENC[AES256_GCM,data:fkYi2gv/XHvIdPGN+Hd14UvXOHzrOHy4yHJaWFoBEvSRk08n1gnCOibB73nalDhWi+b191kXlKOCBbIsN2KxTF4eKEWtPyLD5vfBrj0qOxeW/wyzgCC0x3uCNF/0v28pg+pf2b4YlXibukp3Xj5iqjSMjJEge2NWr/rko67rhuU=,iv:dPCZUv9vWJy/P9AyideCFXUh77RM3e5k3Tk7lKOEt84=,tag:kkrBrtx+fHqoCoSwCfabxw==,type:str]
    pgp:
        - created_at: "2023-11-21T15:42:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DZSODbPSZIlESAQdACMDDFDP36bOQMj/hBZVNRRl+VrOFVqavFGZpX7ilsgIw
            faJxuWvlnn/pwIiFTcSOfFv0YSReF4pNhWLo3GxmbSdTQKyCjEg6CYcCiHEuGsHm
            0l4BaVhyj18KPsSHVv8ZZgA74Nr8SFILZAwgzNV8sd7QEfH7zizSIByPMbZfrQe/
            SrzY9yLNIeWEtl95pdat5cB7EpaAwCO7jk5EM9+i3c/Ml77KWwDpjlU61qZ9wP8O
            =wHJG
            -----END PGP MESSAGE-----
          fp: 8CC5C91F72DB57DA20BD848C6523836CF4992251
    unencrypted_suffix: _unencrypted
    version: 3.8.1
